kotlin version: 2.0.0
error message: Incremental compilation failed: Failed to close caches
org.jetbrains.kotlin.incremental.CachesManagerCloseException: Failed to close caches
	at org.jetbrains.kotlin.incremental.BaseCompilationTransaction.closeCachesManager(CompilationTransaction.kt:126)
	at org.jetbrains.kotlin.incremental.RecoverableCompilationTransaction.close(CompilationTransaction.kt:251)
	at org.jetbrains.kotlin.incremental.IncrementalCompilerRunner.tryCompileIncrementally(IncrementalCompilerRunner.kt:747)
	at org.jetbrains.kotlin.incremental.IncrementalCompilerRunner.compile(IncrementalCompilerRunner.kt:120)
	at org.jetbrains.kotlin.daemon.CompileServiceImplBase.execIncrementalCompiler(CompileServiceImpl.kt:676)
	at org.jetbrains.kotlin.daemon.CompileServiceImplBase.access$execIncrementalCompiler(CompileServiceImpl.kt:92)
	at org.jetbrains.kotlin.daemon.CompileServiceImpl.compile(CompileServiceImpl.kt:1661)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at java.rmi/sun.rmi.server.UnicastServerRef.dispatch(Unknown Source)
	at java.rmi/sun.rmi.transport.Transport$1.run(Unknown Source)
	at java.rmi/sun.rmi.transport.Transport$1.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at java.rmi/sun.rmi.transport.Transport.serviceCall(Unknown Source)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport.handleMessages(Unknown Source)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run0(Unknown Source)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.lambda$run$0(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.lang.AssertionError: C:\Users\piyus\OneDrive\Desktop\Projects\FoodDelivery\app\build\kotlin\kaptGenerateStubsDebugKotlin\cacheable\caches-jvm\lookups\lookups.tab: The process cannot access the file because it is being used by another process
	at org.jetbrains.kotlin.com.intellij.openapi.diagnostic.DefaultLogger.error(DefaultLogger.java:54)
	at org.jetbrains.kotlin.com.intellij.openapi.diagnostic.Logger.error(Logger.java:208)
	at org.jetbrains.kotlin.com.intellij.util.io.FilePageCache.disposeRemovedSegments(FilePageCache.java:193)
	at org.jetbrains.kotlin.com.intellij.util.io.FilePageCache.unmapBuffersForOwner(FilePageCache.java:269)
	at org.jetbrains.kotlin.com.intellij.util.io.PagedFileStorage.unmapAll(PagedFileStorage.java:257)
	at org.jetbrains.kotlin.com.intellij.util.io.PagedFileStorage.lambda$close$3(PagedFileStorage.java:244)
	at org.jetbrains.kotlin.com.intellij.util.ExceptionUtil.runAndCatch(ExceptionUtil.java:149)
	at org.jetbrains.kotlin.com.intellij.util.io.PagedFileStorage.close(PagedFileStorage.java:243)
	at org.jetbrains.kotlin.com.intellij.util.io.ResizeableMappedFile.lambda$close$2(ResizeableMappedFile.java:249)
	at org.jetbrains.kotlin.com.intellij.util.ExceptionUtil.runAndCatch(ExceptionUtil.java:149)
	at org.jetbrains.kotlin.com.intellij.util.io.ResizeableMappedFile.close(ResizeableMappedFile.java:249)
	at org.jetbrains.kotlin.com.intellij.util.io.IntToIntBtree.doClose(IntToIntBtree.java:280)
	at org.jetbrains.kotlin.com.intellij.util.io.PersistentBTreeEnumerator.doClose(PersistentBTreeEnumerator.java:310)
	at org.jetbrains.kotlin.com.intellij.util.io.PersistentEnumeratorBase.close(PersistentEnumeratorBase.java:464)
	at org.jetbrains.kotlin.com.intellij.util.io.PersistentBTreeEnumerator.close(PersistentBTreeEnumerator.java:650)
	at org.jetbrains.kotlin.com.intellij.util.io.PersistentMapImpl.doClose(PersistentMapImpl.java:812)
	at org.jetbrains.kotlin.com.intellij.util.io.PersistentMapImpl.close(PersistentMapImpl.java:780)
	at org.jetbrains.kotlin.com.intellij.util.io.PersistentMapImpl.close(PersistentMapImpl.java:760)
	at org.jetbrains.kotlin.com.intellij.util.io.PersistentHashMap.close(PersistentHashMap.java:203)
	at org.jetbrains.kotlin.incremental.storage.LazyStorage.close(LazyStorage.kt:93)
	at org.jetbrains.kotlin.incremental.storage.InMemoryStorage.close(InMemoryStorage.kt:137)
	at org.jetbrains.kotlin.incremental.storage.AppendableSetBasicMap.close(BasicMap.kt:157)
	at org.jetbrains.kotlin.incremental.storage.BasicMapsOwner$close$1.invoke(BasicMapsOwner.kt:45)
	at org.jetbrains.kotlin.incremental.storage.BasicMapsOwner$close$1.invoke(BasicMapsOwner.kt:45)
	at org.jetbrains.kotlin.incremental.storage.BasicMapsOwner.forEachMapSafe(BasicMapsOwner.kt:85)
	at org.jetbrains.kotlin.incremental.storage.BasicMapsOwner.close(BasicMapsOwner.kt:45)
	at org.jetbrains.kotlin.incremental.LookupStorage.close(LookupStorage.kt:155)
	at org.jetbrains.kotlin.com.google.common.io.Closer.close(Closer.java:218)
	at org.jetbrains.kotlin.incremental.IncrementalCachesManager.close(IncrementalCachesManager.kt:55)
	at org.jetbrains.kotlin.incremental.BaseCompilationTransaction.closeCachesManager(CompilationTransaction.kt:123)
	... 21 more
	Suppressed: java.lang.AssertionError: C:\Users\piyus\OneDrive\Desktop\Projects\FoodDelivery\app\build\kotlin\kaptGenerateStubsDebugKotlin\cacheable\caches-jvm\lookups\lookups.tab: The process cannot access the file because it is being used by another process
		at org.jetbrains.kotlin.com.intellij.openapi.diagnostic.DefaultLogger.error(DefaultLogger.java:54)
		at org.jetbrains.kotlin.com.intellij.openapi.diagnostic.Logger.error(Logger.java:208)
		at org.jetbrains.kotlin.com.intellij.util.io.FilePageCache.disposeRemovedSegments(FilePageCache.java:193)
		at org.jetbrains.kotlin.com.intellij.util.io.FilePageCache.unmapBuffersForOwner(FilePageCache.java:269)
		at org.jetbrains.kotlin.com.intellij.util.io.PagedFileStorage.unmapAll(PagedFileStorage.java:257)
		at org.jetbrains.kotlin.com.intellij.util.io.PagedFileStorage.lambda$close$3(PagedFileStorage.java:244)
		at org.jetbrains.kotlin.com.intellij.util.ExceptionUtil.runAndCatch(ExceptionUtil.java:149)
		at org.jetbrains.kotlin.com.intellij.util.io.PagedFileStorage.close(PagedFileStorage.java:243)
		at org.jetbrains.kotlin.com.intellij.util.io.ResizeableMappedFile.lambda$close$2(ResizeableMappedFile.java:249)
		at org.jetbrains.kotlin.com.intellij.util.ExceptionUtil.runAndCatch(ExceptionUtil.java:149)
		at org.jetbrains.kotlin.com.intellij.util.io.ResizeableMappedFile.close(ResizeableMappedFile.java:249)
		at org.jetbrains.kotlin.com.intellij.util.io.IntToIntBtree.doClose(IntToIntBtree.java:280)
		at org.jetbrains.kotlin.com.intellij.util.io.PersistentBTreeEnumerator.doClose(PersistentBTreeEnumerator.java:310)
		at org.jetbrains.kotlin.com.intellij.util.io.PersistentEnumeratorBase.close(PersistentEnumeratorBase.java:464)
		at org.jetbrains.kotlin.com.intellij.util.io.PersistentBTreeEnumerator.close(PersistentBTreeEnumerator.java:650)
		at org.jetbrains.kotlin.com.intellij.util.io.PersistentMapImpl.doClose(PersistentMapImpl.java:812)
		at org.jetbrains.kotlin.com.intellij.util.io.PersistentMapImpl.close(PersistentMapImpl.java:780)
		at org.jetbrains.kotlin.com.intellij.util.io.PersistentMapImpl.close(PersistentMapImpl.java:760)
		at org.jetbrains.kotlin.com.intellij.util.io.PersistentHashMap.close(PersistentHashMap.java:203)
		at org.jetbrains.kotlin.incremental.storage.LazyStorage.close(LazyStorage.kt:93)
		at org.jetbrains.kotlin.incremental.storage.InMemoryStorage.close(InMemoryStorage.kt:137)
		at org.jetbrains.kotlin.incremental.storage.AppendableSetBasicMap.close(BasicMap.kt:157)
		at org.jetbrains.kotlin.incremental.storage.BasicMapsOwner$close$1.invoke(BasicMapsOwner.kt:45)
		at org.jetbrains.kotlin.incremental.storage.BasicMapsOwner$close$1.invoke(BasicMapsOwner.kt:45)
		at org.jetbrains.kotlin.incremental.storage.BasicMapsOwner.forEachMapSafe(BasicMapsOwner.kt:85)
		at org.jetbrains.kotlin.incremental.storage.BasicMapsOwner.close(BasicMapsOwner.kt:45)
		... 24 more
	Caused by: java.nio.file.FileSystemException: C:\Users\piyus\OneDrive\Desktop\Projects\FoodDelivery\app\build\kotlin\kaptGenerateStubsDebugKotlin\cacheable\caches-jvm\lookups\lookups.tab: The process cannot access the file because it is being used by another process
		at java.base/sun.nio.fs.WindowsException.translateToIOException(Unknown Source)
		at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(Unknown Source)
		at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(Unknown Source)
		at java.base/sun.nio.fs.WindowsFileSystemProvider.newFileChannel(Unknown Source)
		at java.base/java.nio.channels.FileChannel.open(Unknown Source)
		at java.base/java.nio.channels.FileChannel.open(Unknown Source)
		at org.jetbrains.kotlin.com.intellij.util.io.UnInterruptibleFileChannelHandle.lambda$reopenChannel$1(UnInterruptibleFileChannelHandle.java:79)
		at org.jetbrains.kotlin.com.intellij.util.ConcurrencyUtil.withLock(ConcurrencyUtil.java:244)
		at org.jetbrains.kotlin.com.intellij.util.io.UnInterruptibleFileChannelHandle.reopenChannel(UnInterruptibleFileChannelHandle.java:78)
		at org.jetbrains.kotlin.com.intellij.util.io.UnInterruptibleFileChannelHandle.<init>(UnInterruptibleFileChannelHandle.java:39)
		at org.jetbrains.kotlin.com.intellij.util.io.UnInterruptibleFileChannel.<init>(UnInterruptibleFileChannel.java:26)
		at org.jetbrains.kotlin.com.intellij.util.io.OpenChannelsCache$ChannelDescriptor.lambda$new$0(OpenChannelsCache.java:112)
		at org.jetbrains.kotlin.com.intellij.openapi.util.io.FileUtilRt.doIOOperation(FileUtilRt.java:947)
		at org.jetbrains.kotlin.com.intellij.util.io.OpenChannelsCache$ChannelDescriptor.<init>(OpenChannelsCache.java:110)
		at org.jetbrains.kotlin.com.intellij.util.io.PagedFileStorage.useChannel(PagedFileStorage.java:129)
		at org.jetbrains.kotlin.com.intellij.util.io.DirectBufferWrapper.force(DirectBufferWrapper.java:148)
		at org.jetbrains.kotlin.com.intellij.util.io.DirectBufferWrapper.release(DirectBufferWrapper.java:130)
		at org.jetbrains.kotlin.com.intellij.util.io.FilePageCache.disposeRemovedSegments(FilePageCache.java:190)
		... 47 more
Caused by: java.nio.file.FileSystemException: C:\Users\piyus\OneDrive\Desktop\Projects\FoodDelivery\app\build\kotlin\kaptGenerateStubsDebugKotlin\cacheable\caches-jvm\lookups\lookups.tab: The process cannot access the file because it is being used by another process
	at java.base/sun.nio.fs.WindowsException.translateToIOException(Unknown Source)
	at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(Unknown Source)
	at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(Unknown Source)
	at java.base/sun.nio.fs.WindowsFileSystemProvider.newFileChannel(Unknown Source)
	at java.base/java.nio.channels.FileChannel.open(Unknown Source)
	at java.base/java.nio.channels.FileChannel.open(Unknown Source)
	at org.jetbrains.kotlin.com.intellij.util.io.UnInterruptibleFileChannelHandle.lambda$reopenChannel$1(UnInterruptibleFileChannelHandle.java:79)
	at org.jetbrains.kotlin.com.intellij.util.ConcurrencyUtil.withLock(ConcurrencyUtil.java:244)
	at org.jetbrains.kotlin.com.intellij.util.io.UnInterruptibleFileChannelHandle.reopenChannel(UnInterruptibleFileChannelHandle.java:78)
	at org.jetbrains.kotlin.com.intellij.util.io.UnInterruptibleFileChannelHandle.<init>(UnInterruptibleFileChannelHandle.java:39)
	at org.jetbrains.kotlin.com.intellij.util.io.UnInterruptibleFileChannel.<init>(UnInterruptibleFileChannel.java:26)
	at org.jetbrains.kotlin.com.intellij.util.io.OpenChannelsCache$ChannelDescriptor.lambda$new$0(OpenChannelsCache.java:112)
	at org.jetbrains.kotlin.com.intellij.openapi.util.io.FileUtilRt.doIOOperation(FileUtilRt.java:947)
	at org.jetbrains.kotlin.com.intellij.util.io.OpenChannelsCache$ChannelDescriptor.<init>(OpenChannelsCache.java:110)
	at org.jetbrains.kotlin.com.intellij.util.io.PagedFileStorage.useChannel(PagedFileStorage.java:129)
	at org.jetbrains.kotlin.com.intellij.util.io.DirectBufferWrapper.force(DirectBufferWrapper.java:148)
	at org.jetbrains.kotlin.com.intellij.util.io.DirectBufferWrapper.release(DirectBufferWrapper.java:130)
	at org.jetbrains.kotlin.com.intellij.util.io.FilePageCache.disposeRemovedSegments(FilePageCache.java:190)
	... 48 more


error message: Daemon compilation failed: null
java.lang.Exception
	at org.jetbrains.kotlin.daemon.common.CompileService$CallResult$Error.get(CompileService.kt:69)
	at org.jetbrains.kotlin.daemon.common.CompileService$CallResult$Error.get(CompileService.kt:65)
	at org.jetbrains.kotlin.compilerRunner.GradleKotlinCompilerWork.compileWithDaemon(GradleKotlinCompilerWork.kt:240)
	at org.jetbrains.kotlin.compilerRunner.GradleKotlinCompilerWork.compileWithDaemonOrFallbackImpl(GradleKotlinCompilerWork.kt:159)
	at org.jetbrains.kotlin.compilerRunner.GradleKotlinCompilerWork.run(GradleKotlinCompilerWork.kt:111)
	at org.jetbrains.kotlin.compilerRunner.GradleCompilerRunnerWithWorkers$GradleKotlinCompilerWorkAction.execute(GradleCompilerRunnerWithWorkers.kt:76)
	at org.gradle.workers.internal.DefaultWorkerServer.execute(DefaultWorkerServer.java:63)
	at org.gradle.workers.internal.NoIsolationWorkerFactory$1$1.create(NoIsolationWorkerFactory.java:66)
	at org.gradle.workers.internal.NoIsolationWorkerFactory$1$1.create(NoIsolationWorkerFactory.java:62)
	at org.gradle.internal.classloader.ClassLoaderUtils.executeInClassloader(ClassLoaderUtils.java:100)
	at org.gradle.workers.internal.NoIsolationWorkerFactory$1.lambda$execute$0(NoIsolationWorkerFactory.java:62)
	at org.gradle.workers.internal.AbstractWorker$1.call(AbstractWorker.java:44)
	at org.gradle.workers.internal.AbstractWorker$1.call(AbstractWorker.java:41)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:209)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:204)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:66)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:59)
	at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:166)
	at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:59)
	at org.gradle.internal.operations.DefaultBuildOperationRunner.call(DefaultBuildOperationRunner.java:53)
	at org.gradle.workers.internal.AbstractWorker.executeWrappedInBuildOperation(AbstractWorker.java:41)
	at org.gradle.workers.internal.NoIsolationWorkerFactory$1.execute(NoIsolationWorkerFactory.java:59)
	at org.gradle.workers.internal.DefaultWorkerExecutor.lambda$submitWork$0(DefaultWorkerExecutor.java:174)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at org.gradle.internal.work.DefaultConditionalExecutionQueue$ExecutionRunner.runExecution(DefaultConditionalExecutionQueue.java:194)
	at org.gradle.internal.work.DefaultConditionalExecutionQueue$ExecutionRunner.access$700(DefaultConditionalExecutionQueue.java:127)
	at org.gradle.internal.work.DefaultConditionalExecutionQueue$ExecutionRunner$1.run(DefaultConditionalExecutionQueue.java:169)
	at org.gradle.internal.Factories$1.create(Factories.java:31)
	at org.gradle.internal.work.DefaultWorkerLeaseService.withLocks(DefaultWorkerLeaseService.java:263)
	at org.gradle.internal.work.DefaultWorkerLeaseService.runAsWorkerThread(DefaultWorkerLeaseService.java:127)
	at org.gradle.internal.work.DefaultWorkerLeaseService.runAsWorkerThread(DefaultWorkerLeaseService.java:132)
	at org.gradle.internal.work.DefaultConditionalExecutionQueue$ExecutionRunner.runBatch(DefaultConditionalExecutionQueue.java:164)
	at org.gradle.internal.work.DefaultConditionalExecutionQueue$ExecutionRunner.run(DefaultConditionalExecutionQueue.java:133)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
	at org.gradle.internal.concurrent.AbstractManagedExecutor$1.run(AbstractManagedExecutor.java:48)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.io.IOException: Could not delete 'C:\Users\piyus\OneDrive\Desktop\Projects\FoodDelivery\app\build\kotlin\kaptGenerateStubsDebugKotlin\cacheable\caches-jvm'
	at org.jetbrains.kotlin.incremental.FileUtilsKt.deleteRecursivelyOrThrow(fileUtils.kt:47)
	at org.jetbrains.kotlin.incremental.FileUtilsKt.deleteDirectoryContents(fileUtils.kt:38)
	at org.jetbrains.kotlin.incremental.IncrementalCompilerRunner.cleanOrCreateDirectories(IncrementalCompilerRunner.kt:321)
	at org.jetbrains.kotlin.incremental.IncrementalCompilerRunner.compileNonIncrementally(IncrementalCompilerRunner.kt:290)
	at org.jetbrains.kotlin.incremental.IncrementalCompilerRunner.compile(IncrementalCompilerRunner.kt:148)
	at org.jetbrains.kotlin.daemon.CompileServiceImplBase.execIncrementalCompiler(CompileServiceImpl.kt:676)
	at org.jetbrains.kotlin.daemon.CompileServiceImplBase.access$execIncrementalCompiler(CompileServiceImpl.kt:92)
	at org.jetbrains.kotlin.daemon.CompileServiceImpl.compile(CompileServiceImpl.kt:1661)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at java.rmi/sun.rmi.server.UnicastServerRef.dispatch(Unknown Source)
	at java.rmi/sun.rmi.transport.Transport$1.run(Unknown Source)
	at java.rmi/sun.rmi.transport.Transport$1.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at java.rmi/sun.rmi.transport.Transport.serviceCall(Unknown Source)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport.handleMessages(Unknown Source)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run0(Unknown Source)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.lambda$run$0(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run(Unknown Source)
	... 3 more


